name: Deno

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run linter
        run: deno lint

      - name: Compile HmSYS
        run: deno run --config=tsconfig.json -A --no-check ./compile.ts

      - name: Upload to Development Server
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.WEBSERVER_HOSTNAME }}
          user: ${{ secrets.WEBSERVER_USERNAME }}
          pass: ${{ secrets.WEBSERVER_PASSWORD }}
          port: ${{ secrets.WEBSERVER_PORT }}
          local: "./out"
          remote: ~/remod/laputa/
